---
# The data names listed below won't be deleted
# exceptionData: ["ExceptionFolderName1", "ExceptionFolderName2"]
exceptionData: []

# Will start cleaning after ... seconds
# Increase this value if the plugins in your server have a long load time
delayTime: 1 # Seconds
...
