---
# The data names listed below won't be deleted
# exceptionData: ["ExceptionFolderName1", "ExceptionFolderName2"]
exceptionData: []

# Notification of deleted datas on console
deleteMessageMode: true

# Message on the console when a certain folder is cleaned
# This option will be disabled if deleteMessageMode: false
# {data} : Deleted data name
# {dataType} : Deleted folder type
deleteMessage: "&aDeleted: &b{data} &6[{dataType}]"

# Will start cleaning after ... seconds
# Increase this value if the plugins in your server have a long load time
delayTime: 1 # Seconds

# Config version
configVersion: "1.0.0" # Please don't edit or delete this line
...
